data = [
    ("MV/RC", "The horse raced past the barn fell.", "The horse that raced past the barn fell."),
    ("MV/RC","The cotton clothing is made of grows in Mississippi.", "The cotton that clothing is made of grows in Mississippi"),
    ("MV/RC","Vaccine trials halted after a patient fell ill restart. ", "Vaccine trials, which were halted after a patient fell ill, restart."),
    ("MV/RC","The florist sent the flowers was rather pleased.", "The florist who was sent the flowers was rather pleased."),
    ("MV/RC","The performer sent the flowers was rather pleased.", "The performer who was sent the flowers was rather pleased."),
    ("MV/RC","The girl told the story cried.", "The girl who was told the story cried."),
    ("MV/RC","The boat floated down the river sank.", "The boat that floated down the river sank."),
    ("MV/RC","The postman delivered junk mail threw it into the trash.", "The postman who was delivered junk mail threw it into the trash."),
    ("MV/RC","The man gifted a ring played the piano.", "The man who was gifted a ring played the piano."),
    ("MV/RC","The old man told the story complained to his son", "The old man who was told the story complained to his son."),
    ("NP/Z","As the criminal shot the woman yelled at the top of her lungs.", "As the criminal shot, the woman yelled at the top of her lungs."),
    ("NP/Z","As the doctor studied the textbook fell to the floor.", "As the doctor studied, the textbook fell to the floor."),
    ("NP/Z","Since Jay always jogs a mile seems a short distance to him.", "Since Jay always jogs, a mile seems a short distance to him."),
    ("NP/Z","When the dog scratched the vet with his new assistant took off the muzzle.",  "When the dog struggled the vet with his new assistant took off the muzzle."),
    ("NP/Z","The man who whistles tunes pianos.", "The man who whistles is tuning pianos"),
    ("NP/Z","Because Bill drinks wine is never kept in the house.", "Because Bill drinks, wine is never kept in the house."),
    ("NP/Z","When the boys strike the dog kills.", "When the boys strike, the dog kills."),
    ("NP/Z","After the Martians invaded the town was evacuated.", "After the Martians invaded, the town was evacuated."),
    ("NP/Z","The man who hunts ducks out on weekends.", "The hunter ducks out on weekends."),
    ("NP/Z","As the woman photographed a bird sang beautifully.", "As the woman photographed, a bird sang beautifully."),
    ("NP/Z","As the artist was painting the portrait fell to the ground.", "As the artist was painting, the portrait fell to the ground."),
    ("NP/Z","While my mum was cooking pasta boiled in the pot.", "While my mum was cooking, pasta boiled in the pot."),
    ("NP/Z","While the nurse shaved the patient who was tired and weak watched TV.", "While the nurse shaved, the patient who was tired and weak watched TV."),
    ("NP/Z", "While the orchestra performed the symphony played on the radio.", "While the orchestra performed, the symphony played on the radio"),
    ("NP/Z", "While the lawyer studied the contract lay on the desk.", "While the lawyer studied, the contract lay on the desk."),
    ("NP/Z", "While Rick drove the car that was red and dusty veered into a ditch.", "While Rick drove, the car that was red and dusty veered into a ditch."),
    ("NP/Z","While the secretary typed the memo that was clear and concise neared completion.", "While the secretary typed, the memo that was clear and concise neared completion."),
    ("NP/Z", "As John whittled the wooden stick broke in half.", "As John whittled, the wooden stick broke in half."),
    ("NP/Z", "While the mother calmed down the children who were irritable and tired sat on the bed.", "While the mother calmed down, the children who were irritable and tired sat on the bed."),
    ("NP/Z", "While the farmer steered the tractor pulled the plough.", "While the farmer steered, the tractor pulled the plough."),
    ("NP/Z", "While the chimps groomed the baboons that were large and hairy sat in the grass.", "While the chimps groomed, the baboons that were large and hairy sat in the grass."),
    ("NP/Z", "Without greeting the man ran away", "Without greeting, the man ran away"),
    ("NP/Z","After the Martians invaded the town the city bordered the people were evacuated.", "After the Martians invaded the town that the city bordered, the people were evacuated."),
    ("NP/Z","While Bill hunted the deer ran into the woods.", "While Bill hunted, the deer ran into the woods."),
    ("NP/Z","While Anna bathed the kid played in the crib.", "While Anna bathed, the kid played in the crib."),
    ("NP/S", "The explorers found the South Pole was impossible to reach.", "The explorers found that the South Pole was impossible to reach."),
    ("NP/S", "The teacher knew the student had been struggling for a while.", "The teacher knew that the student had been struggling for a while."),
    ("NP/S", "The fan finally saw his favorite baseball player had taken the field.", "The fan finally saw that his favorite baseball player had taken the field."),
    ("NP/S", "The director announced the cast would change.", "The director announced that the cast would change."),
    ("NP/S", "The mum saw her child had finished eating.", "The mum saw that her child had finished eating."),
    ("NP/S", "The girl noticed a spot was staining the wall.", "The girl noticed that a spot was staining the wall."),
    ("NP/S", "Henry eventually realized his mistake could not be fixed.", "Henry eventually realized that his mistake could not be fixed."),
    ("NP/S","The employees read the contract would expire very soon.", "The employees read that the contract would expire very soon."),
    ("NP/S", "The professor warned the student was late.", "The professor warned that the student was late."),
    ("NP/S", "The journalist read the magazine had been closed.", "The journalist read that the magazine had been closed."),
    ("NP/S", "Gyada knows the old woman is being honest.", "Gyada knows that the old woman is being honest."),
    ("NP/S", "She told her daughter a dream could be achieved.", "She told her daughter that a dream could be achieved."),
    ("Categorical","Fat people eat accumulates.", "Fat that people eat accumulates."),
    ("Categorical","The building blocks the sun faded are red.", "The building blocks that the sun faded are red."),
    ("Categorical","The old man the boats.", "The old people manage the boats."),
    ("Categorical","The complex houses married soldiers and their families.", "Married soldiers and their families are housed in the complex."),
    ("Categorical","The granite rocks by the seashore with the waves.", "It is the granite that rocks by the seashore with the waves."),
    ("Categorical","The prime number few.", "Prime individuals count few members."),
    ("Categorical","The sour drink from the ocean.", "Sour people drink from the ocean."),
    ("Categorical","The tired run late at night.", "The tired people run late at night."),
    ("Categorical","The experienced coach the football team.", "The experienced players coach the football team."),
    ("Categorical","The young soldier the barracks at dawn.", "The young people soldier the barracks at dawn."),
    ("Categorical","The joyful band the parade.", "The joyful musicians band the parade."),

]